// Interface automatically generated by schemas-to-ts

import { Post } from '../../../post/content-types/post/post';
import { Post_Plain } from '../../../post/content-types/post/post';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Tag {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    posts?: { data: Post[] };
  };
}
export interface Tag_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  posts?: Post_Plain[];
}

export interface Tag_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  posts?: number[];
}

export interface Tag_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  posts?: AdminPanelRelationPropertyModification<Post_Plain>;
}
