// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Post } from '../../../post/content-types/post/post';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Post_Plain } from '../../../post/content-types/post/post';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Author {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    Email: string;
    bio?: string;
    avatar?: { data: Media };
    posts: { data: Post[] };
  };
}
export interface Author_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  Email: string;
  bio?: string;
  avatar?: Media_Plain;
  posts: Post_Plain[];
}

export interface Author_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  Email: string;
  bio?: string;
  avatar?: number;
  posts: number[];
}

export interface Author_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  Email: string;
  bio?: string;
  avatar?: AdminPanelRelationPropertyModification<Media_Plain>;
  posts: AdminPanelRelationPropertyModification<Post_Plain>;
}
