// Interface automatically generated by schemas-to-ts

import { Post } from '../../../post/content-types/post/post';
import { Post_Plain } from '../../../post/content-types/post/post';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Comment {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    content: string;
    authorName: string;
    authorEmail: string;
    approved?: boolean;
    post?: { data: Post };
  };
}
export interface Comment_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content: string;
  authorName: string;
  authorEmail: string;
  approved?: boolean;
  post?: Post_Plain;
}

export interface Comment_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content: string;
  authorName: string;
  authorEmail: string;
  approved?: boolean;
  post?: number;
}

export interface Comment_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  content: string;
  authorName: string;
  authorEmail: string;
  approved?: boolean;
  post?: AdminPanelRelationPropertyModification<Post_Plain>;
}
