// Interface automatically generated by schemas-to-ts

import { Media } from '../../../../common/schemas-to-ts/Media';
import { Author } from '../../../author/content-types/author/author';
import { Category } from '../../../category/content-types/category/category';
import { Tag } from '../../../tag/content-types/tag/tag';
import { Comment } from '../../../comment/content-types/comment/comment';
import { Media_Plain } from '../../../../common/schemas-to-ts/Media';
import { Author_Plain } from '../../../author/content-types/author/author';
import { Category_Plain } from '../../../category/content-types/category/category';
import { Tag_Plain } from '../../../tag/content-types/tag/tag';
import { Comment_Plain } from '../../../comment/content-types/comment/comment';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Post {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    title: string;
    slug: string;
    content: string;
    coverImage?: { data: Media };
    published_date?: Date;
    author?: { data: Author };
    category?: { data: Category };
    tags?: { data: Tag[] };
    comments: { data: Comment[] };
  };
}
export interface Post_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  content: string;
  coverImage?: Media_Plain;
  published_date?: Date;
  author?: Author_Plain;
  category?: Category_Plain;
  tags?: Tag_Plain[];
  comments: Comment_Plain[];
}

export interface Post_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  content: string;
  coverImage?: number;
  published_date?: Date;
  author?: number;
  category?: number;
  tags?: number[];
  comments: number[];
}

export interface Post_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  title: string;
  slug: string;
  content: string;
  coverImage?: AdminPanelRelationPropertyModification<Media_Plain>;
  published_date?: Date;
  author?: AdminPanelRelationPropertyModification<Author_Plain>;
  category?: AdminPanelRelationPropertyModification<Category_Plain>;
  tags?: AdminPanelRelationPropertyModification<Tag_Plain>;
  comments: AdminPanelRelationPropertyModification<Comment_Plain>;
}
