// Interface automatically generated by schemas-to-ts

import { Post } from '../../../post/content-types/post/post';
import { Post_Plain } from '../../../post/content-types/post/post';
import { AdminPanelRelationPropertyModification } from '../../../../common/schemas-to-ts/AdminPanelRelationPropertyModification';

export interface Category {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    name: string;
    slug: string;
    description?: string;
    posts: { data: Post[] };
  };
}
export interface Category_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  description?: string;
  posts: Post_Plain[];
}

export interface Category_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  description?: string;
  posts: number[];
}

export interface Category_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  name: string;
  slug: string;
  description?: string;
  posts: AdminPanelRelationPropertyModification<Post_Plain>;
}
