// Interface automatically generated by schemas-to-ts

export interface Newsletter {
  id: number;
  attributes: {
    createdAt: Date;    updatedAt: Date;    publishedAt?: Date;    email: string;
  };
}
export interface Newsletter_Plain {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email: string;
}

export interface Newsletter_NoRelations {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email: string;
}

export interface Newsletter_AdminPanelLifeCycle {
  id: number;
  createdAt: Date;  updatedAt: Date;  publishedAt?: Date;  email: string;
}
